---
version: "3.3"

services:
  main:
    build: .
    ports:
      - "8081:8081"
    environment:
      # logging
      LOG_LEVEL: "debug"
      CRON_SCHEDULE: "* * * * *"
      DOMAINS: "michaelpeterswa.com,mptrswa.com,cascades.dev,cascadelabs.dev,halcyonresearch.dev,nw.codes,shrt.fyi,nwst.us,676f.dev,letterkenny.dev"
